CREATE DATABASE IF NOT EXISTS prevenda_db;
USE prevenda_db;

CREATE TABLE IF NOT EXISTS interessados (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    quantidade INT NOT NULL,
    aceita_notificacoes BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
